from .registration import Registration

from .bone_registration import BoneRegistration
from .component_registration import ComponentRegistration
from .property_holder_registration import PropertyHolderRegistration
